version: "3.9"
services:
  liquidsoap:
    build:
      args:
        - UID
        - USER
      context: .
      target: development
    init: true
    ports:
      # Harbor SSL
      - 8200:8000
    volumes:
      - /home/${USER}/.cache/yarn:/home/${USER}/.cache/yarn
      - ${PWD}:/app
